### ISSUE TITLE
CIVIL is incorrectly denormalised as 153

### ISSUE THREAD

**Issue by microadam** [qbunt/romans#16]
Useful little project! Found this odd edge case. 153 should be CLIII

**Comment by qbunt** [comment]
hey @microadam thanks! I wrote a test case for this and it's passing in the ES6 rewrite of this. Should be able to push it out some point tomorrow

**Comment by qbunt** [comment]
The test I mentioned https://github.com/qbunt/romans/blob/9818b879d9462676c1f84e03f608bf39dd3d2426/test/main.test.js#L33-L36
is passing in the latest build locally and [in CI](https://github.com/qbunt/romans/runs/3271898402?check_suite_focus=true#step:5:16), so I think this is taken care of now. Hope this works for you, thanks for the issue!

**Comment by microadam** [comment]
Hi @qbunt! Thanks for taking a look. I think the original issue still persists though (to be honest, my original issue wasn't clear enough!). So the code `romans.deromanize("CIVIL")` returns 153, but it should return `NaN` as It isn't a valid roman numeral. 153 is `CLIII`. Hope that clarifies!

**Comment by qbunt** [comment]
Finally had a little time to release a patch https://github.com/qbunt/romans/releases/tag/v1.1.3 with some validation fixes to close this guy. Thanks for filing the bug, have a good one 🚀

**Comment by microadam** [comment]
Hi @qbunt! Thanks for solving. I would suggest unpublishing / deprecating that version and republishing this as a major version change though, as you have changed the API in the latest release. Previously, an invalid roman numeral would return `NaN`, now it throws an error. Anyone expecting that old behaviour will have their applications broken if they are not careful

**Comment by qbunt** [comment]
@microadam deprecated and repub'd as v2.0.0+ thanks

**Comment by microadam** [comment]
Thank you! :)
